create table Book (
  id int generated by default as identity (start with 1) primary key,
  title varchar(25) not null,
  author varchar(25) not null,
  publication_date varchar(100) not null,
  edition int not null
);

INSERT INTO Book (id, title, author, publication_date, edition) VALUES
    (1, 'The Great Gatsby', 'F. Scott Fitzgerald', '1925-04-10', 1),
    (2, 'To Kill a Mockingbird', 'Harper Lee', '1960-07-11', 1),
    (3, '1984', 'George Orwell', '1949-06-08', 1),
    (4, 'Animal Farm', 'George Orwell', '1945-08-17', 1),
    (5, 'Pride and Prejudice', 'Jane Austen', '1813-01-28', 1);
